ST-Apps/PoGo-UWP

- PokemonGo-UWP/ViewModels/GameManagerViewModel.cs
Sometimes NullReferenceException appears
> Fix crash on closing

- PokemonGo-UWP/ViewModels/GameManagerViewModel.cs
Forced update was causing two updates to happen back to back which caused issues with data loading
> Correct the issue with forced update, #15

- README.md
> Updated README.md to the latest version

- PokemonGo-UWP/Styles/Custom.xaml
you can use this style with this line of code:
`<Button Style="{StaticResource ButtonSubmit}"><TextBlock Text="ENABLE" /></Button>`
or
`<Button Style="{StaticResource ButtonCircle}"></Button>`
Note, you have to set the FontFamily.
> New Buttons Style (Niantic)

- PokemonGo-UWP/Views/MainPage.xaml.cs
Hiding keyboard on pressing return key in password box by setting the
focus on loginbutton.
> Hiding keyboard on pressing return key in password box

- PokemonGo-UWP/Styles/Custom.xaml
- PokemonGo-UWP/Views/StyleElementPreviewPage.xaml
- PokemonGo-UWP/Views/StyleElementPreviewPage.xaml.cs
- Fixed old style
- Added new Style
- Added new page for show what developers can build with new style
> More Style! 

- PokemonGoAPI/Login/GSPOAuthSharp.cs
Without 2FA. Use app-password for now
> Implements the necessary encryptions to make Google Login possible

- README.md
> Update README.md (Why the hell are you removing the groups?!)

- PokemonGo-UWP/Views/MainPage.xaml
responsable -> responsible
Tiny typo :)
> Typo on MainPage.xaml

- PokemonGo-UWP/PokemonGo-UWP.csproj
- PokemonGo-UWP/Strings/fr-FR/Items.resw
- PokemonGo-UWP/Strings/fr-FR/Pokemon.resw
- PokemonGo-UWP/Strings/fr-FR/Resources.resw
Now, I've added French translations for Pokémons and Items, also.
> #312, #64: Added french Pokemon and items translations.

- PokemonGo-UWP/Strings/fr-FR/Resources.resw
French translation completed on Resources
> French translation

- PokemonGo-UWP/PokemonGo-UWP.csproj
- PokemonGo-UWP/Strings/tr-TR/Items.resw
- PokemonGo-UWP/Strings/tr-TR/Pokemon.resw
- PokemonGo-UWP/Strings/tr-TR/Resources.resw
Added the Files provided in #414
> Added Turkish translation

- PokemonGo-UWP/Strings/ru-RU/Items.resw
I made a new update for Russian Translation!
Added:
1. Added Description Support.
Fixed:
1. Fixed some mistakes.
> Added Description Support for Russian

- PokemonGo-UWP/Strings/cs-CZ/Items.resw
Got my github plugin to work somehow, so I translated the item descriptions to czech :)
> Translated the item descriptions (Czech)

- PokemonGo-UWP/Strings/it-IT/Resources.resw
More translations for the "Resources" file.
> Added translations to Resources.resw

- PokemonGo-UWP/Strings/pt-BR/Items.resw
- PokemonGo-UWP/Strings/pt-BR/Pokemon.resw
- PokemonGo-UWP/Strings/pt-BR/Resources.resw
Translation of items and resources to Brazilian Portuguese.
> Brasilian Portuguese translation

- PokemonGo-UWP/PokemonGo-UWP.csproj
- PokemonGo-UWP/Strings/cs-CZ/Resources.resw
- PokemonGo-UWP/Strings/sk-SK/Items.resw
- PokemonGo-UWP/Strings/sk-SK/Pokemon.resw
- PokemonGo-UWP/Strings/sk-SK/Resources.resw
Translated the newest resource changes :)
My slovak translation might seem a bit shitty to native speakers, don't worry to update it :)
> Translated Resources + Added Slovak language (My translation with help of #64)

- README.md
Grammatical errors + Factual ones
> Fixed misstakes in the Readme

- PokemonGo-UWP/Strings/en-US/Resources.resw
New messages broked by someone...
> Another resources fixes

- PokemonGo-UWP/Strings/ru-RU/Resources.resw
> level up translate #463

- PokemonGo-UWP/Strings/en-US/Resources.resw
Should be fine now, missed them previously
> Another^2 resource fixes

- PokemonGo-UWP/Strings/cs-CZ/Resources.resw
- PokemonGo-UWP/Strings/en-US/Resources.resw
- PokemonGo-UWP/Strings/it-IT/Resources.resw
- PokemonGo-UWP/Strings/ja-JP/Resources.resw
- PokemonGo-UWP/Strings/ru-RU/Items.resw
- PokemonGo-UWP/Strings/ru-RU/Resources.resw
- PokemonGo-UWP/Strings/sk-SK/Resources.resw
- PokemonGo-UWP/Views/GameMapPage.xaml
Some corrections in country resource files to adapt to #456
> New translation added for 'Level up!'

- PokemonGo-UWP/Strings/ru-RU/Resources.resw
Update messages translate #464
> Update messages translate

- PokemonGo-UWP/Strings/cs-CZ/Resources.resw
- PokemonGo-UWP/Strings/sk-SK/Resources.resw
Pretty much self describing. I also corected some misstakes :)
> Translated newest changes into Czech and Slovak languages

- PokemonGo-UWP/Strings/ru-RU/Resources.resw
Removed:
1. UpdateVersion1 and UpdateVersion2 Strings.
Added: 
1. UpdateVersion String
Fixed:
1. Ten mistakes.
> [ru-RU] Resources.resw fixes

- PokemonGo-UWP/Strings/gr-GR/Resources.resw
I am also going to do the items.resw tomorrow.
As for pokemon.resw i think i should just write the names to be pronounceable for people so they can call them with their names.
> Added Greek translations [gr-GR] and resources.resw

- PokemonGo-UWP/Strings/nl-NL/Resources.resw
> Some more Dutch translations.

- PokemonGo-UWP/Strings/it-IT/Resources.resw
Ora il file Resources.resw è pronto per essere inserito nel progetto
> Resources.resw aggiornato senza conflitti

- PokemonGo-UWP/Utils/GameClient.cs
- PokemonGo-UWP/ViewModels/EggDetailPageViewModel.cs
- PokemonGo-UWP/ViewModels/PokemonInventoryPageViewModel.cs
Incubators now splitted correctly to free/currently used ones, so the views can have their own collection, aaand tadaamm :)
> fixed incubators

- PokemonGo-UWP/App.xaml
- PokemonGo-UWP/Utils/Converters.cs
- PokemonGo-UWP/Views/EggDetailPage.xaml
renamed, and changed VisibleWhenStringNotEmptyConverter to show StarIncubation button if EggIncubatorId is empty
> Eggs StartIncubation button visibility fix

- PokemonGo-UWP/PokemonGo-UWP.csproj
- PokemonGo-UWP/Utils/SettingsService.cs
- PokemonGo-UWP/ViewModels/SettingsPageViewModel.cs
- PokemonGo-UWP/Views/GameMapPage.xaml.cs
- PokemonGo-UWP/Views/SettingsPage.xaml
- PokemonGoAPI/PokemonGoAPI.csproj
keeping track of map zoom level on exiting the map view, hope this might be helpful
but if someone already worked on it no need to accept the pull request
> addressing issue #358

- PokemonGo-UWP/ViewModels/PokemonInventoryPageViewModel.cs
Fixes the Egg display order to match the official app.
> Fix Egg display order

- PokemonGo-UWP/Strings/it-IT/Resources.resw
Changed the "cooolDown" string translation.
> Little update to Resources.resw

- PokemonGo-UWP/Strings/es-ES/Items.resw
- PokemonGo-UWP/Strings/es-ES/Resources.resw
Translated directly from the games (as far as i could).
Might not be perfect but is still better than the auto translated one.
Pokemon names in Spanish are the same as in English so I didn't touch that file.
Greetings from Argentina!
PS:
Sorry about the tabs marking the entire document as changed :(
> Spanish Translation 1.0

- PokemonGo-UWP/Strings/pt-BR/Resources.resw
Added new values to Resources.resw
> Update Brasilian Portuguese Resources.resw

- PokemonGo-UWP/Views/SearchPokestopPage.xaml
- PokemonGo-UWP/Views/SettingsPage.xaml
> Fixed UI with little screen - SettingsPage and SearchPokestopPage

- PokemonGo-UWP/PokemonGo-UWP.csproj
- PokemonGo-UWP/Utils/DeviceInfos.cs
- PokemonGo-UWP/Utils/GameClient.cs
- PokemonGo-UWP/Utils/RandomExtensions.cs
- PokemonGoAPI/Client.cs
- PokemonGoAPI/Helpers/IDeviceInfos.cs
- PokemonGoAPI/Helpers/RequestBuilder.cs
- PokemonGoAPI/Helpers/Vector.cs
- PokemonGoAPI/PokemonGoAPI.csproj
- PokemonGoAPI/Rpc/BaseRpc.cs
And also it simulates some data if some sensor is missing (iPhone has almost all sensors)
All sensors should be now filled.
(issue #575)
> Sending device data and sensors to server (issue #575)

- PokemonGoAPI/Helpers/RequestBuilder.cs
We dont know how to fill it right, but on iOS its filled
> Fix: activity status made "0 pokestops" issue

- PokemonGo-UWP.Tests/project.json
To make it consistent with the rest of the projects and remove some warnings when building.
> Updated Microsoft.NETCore.UniversalWindowsPlatform in test project

- PokemonGo-UWP/Controls/CircularProgressBar.xaml
- PokemonGo-UWP/Controls/CircularProgressBar.xaml.cs
- PokemonGo-UWP/PokemonGo-UWP.csproj
- PokemonGo-UWP/Views/PlayerProfilePage.xaml
- PokemonGoAPI/PokemonGoAPI.csproj
Added Circular Progressbar for Achiements and Style up to get closer to original
> Added Circular Progressbar for Achievements

- PokemonGo-UWP/Utils/Signature/DeviceInfos.cs
- PokemonGoAPI/Helpers/IDeviceInfos.cs
- PokemonGoAPI/Helpers/RequestBuilder.cs
- PokemonGoAPI/Proto/Data/Battle/BattleType.cs
- PokemonGoAPI/Proto/Data/Capture/CaptureAward.cs
- PokemonGoAPI/Proto/Enums/PokemonRarity.cs
- PokemonGoAPI/Proto/Map/Fort/FortData.cs
- PokemonGoAPI/Proto/Map/MapCell.cs
- PokemonGoAPI/Proto/Map/Pokemon/NearbyPokemon.cs
- PokemonGoAPI/Proto/Networking/Envelopes/RequestEnvelope.cs
- PokemonGoAPI/Proto/Networking/Envelopes/ResponseEnvelope.cs
- PokemonGoAPI/Proto/Networking/Envelopes/Signature.cs
- PokemonGoAPI/Proto/Networking/Envelopes/Unknown6.cs
- PokemonGoAPI/Proto/Networking/Envelopes/Unknown6Response.cs
- PokemonGoAPI/Proto/Networking/Requests/Messages/GetDownloadUrlsMessage.cs
- PokemonGoAPI/Proto/Networking/Requests/Messages/GetPlayerMessage.cs
- PokemonGoAPI/Proto/Networking/Requests/Messages/SetFavoritePokemonMessage.cs
- PokemonGoAPI/Proto/Networking/Responses/CheckCodenameAvailableResponse.cs
- PokemonGoAPI/Proto/Networking/Responses/ClaimCodenameResponse.cs
- PokemonGoAPI/Proto/Networking/Responses/GetDownloadUrlsResponse.cs
- PokemonGoAPI/Proto/Settings/Master/ItemSettings.cs
- PokemonGoAPI/Rpc/Inventory.cs
- Last PROTOs from https://github.com/AeonLucid/POGOProtos
- Signature also in initial request
- Fixed signature timestamp
- More real sensors values
> API improvements

- PokemonGo-UWP/Strings/en-US/CodeResources.resw
- PokemonGo-UWP/Utils/Game/Converters.cs
Translate activity like "CatchPokemon" from resources.
> better activity when catching Pokemon

- PokemonGo-UWP/ViewModels/PlayerProfileViewModel.cs
PlayerProfile.PokemonCaughtByType should return null when player doesn't have any pokemon :(
> fix for new PlayerProfile without pokemons

- PokemonGo-UWP/Entities/PokemonDataWrapper.cs
- PokemonGo-UWP/Strings/en-US/CodeResources.resw
- PokemonGo-UWP/ViewModels/PokemonInventoryPageViewModel.cs
Triple-checked with the official app, and this is the default sort order. Made adjustments based on the last checkin to keep the wrapper but use the incubatedEggs as the foreach iterator instead of the incubators.
> EggIncubator sort fixes + Activity verbiage updates

- PokemonGo-UWP/App.xaml.cs
App.xaml.cs:
- HockeyClient reporting for UnhandledExceptions.
- DisplayRequest improvements.
- #region adjustments
- Initial Live Tile plumbing and implementation. (Multiple options are
coming next).
Note, this version is using my updated ObservableCollectionPlus to make sure the tile is not updated until all new Pokémon are added to it. This is important to first-load performance.
> App.xaml.cs cleanup & Live Tiles

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.es.xlf
Uploaded translation following #604 instruccions. Also, I translated the details of achievements added in #616
> Updated Spanish translation .xlf file

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.zh-CN.xlf
Updated the lastest xlf file into Chinese.
> Updated Simplified Chinese translation.

- PokemonGo-UWP/Utils/GameClient.cs
- PokemonGo-UWP/ViewModels/GameMapPageViewModel.cs
- Removed dependency on ```GameMapPageViewModel.cs``` from ```GameClient.cs```
This is a bit cleaner. I tested it and works like the previouw implementation.
> Light refactoring of #691

- .github/ISSUE_TEMPLATE.md
So users won't miss the last title message
> Add 2 empty lines at the end of ISSUE_TEMPLATE.md

- PokemonGo-UWP/ViewModels/AchievementDetailPageViewModel.cs
- PokemonGo-UWP/ViewModels/PlayerProfileViewModel.cs
- PokemonGo-UWP/Views/AchievementDetailPage.xaml
- PokemonGo-UWP/Views/PlayerProfilePage.xaml
- added Navigation to AchievmentDetailPage
- using DelegateCommand and Bootstrapper Navigation
- refactoring AchievmentDetailPage
- fixing possible NullReference-Exception during Navigation to AchievementDetailPage
> added Navigation to AchievmentDetailPage

- PokemonGo-UWP/Views/PokemonDetailPage.xaml
> Candy name should wrap

- PokemonGo-UWP/Utils/Game/Converters.cs
- fixing FormatException in AchievementDetailPage
(Jogger Achievement)
> FormatException Jogger Achievement fix

- PokemonGo-UWP/Views/PlayerProfilePage.xaml
> Team text added wrapper

- README.md
- Updated first Update
- Striked down the previous update
- Added new changelog (just link to releases)
> Updated readme.md with latest release

- PokemonGo-UWP/Views/PokemonInventoryPage.xaml
Added a count for the Egg and pokemon
now shows:
e.g: 106 / 250 (pokemon)
6 / 9 (Egg)
> Added Count for Egg and Pokemon

- .github/PULL_REQUEST_TEMPLATE.md
Added a pull request template.
> Created Pull request template

- PokemonGo-UWP/App.xaml.cs
- PokemonGo-UWP/Entities/PokemonDataWrapper.cs
- PokemonGo-UWP/ViewModels/SettingsPageViewModel.cs
- Moved Live Tile updating to a different thread (where available).
- Improved error handling (I believe this fixes issue #805)
- Misc optimizations and sorting fixes.
- Still need to figure out how to remove existing scheduled updates.
> Live Tile Perf Improvements

- PokemonGo-UWP/Utils/Helpers/StorageHelper.cs
#Fixes:
- getting file throws FileNotFoundException: Fixed by creting the file, if it already exists it will be opened.
> Fixed getting folder throws FileNotFound exception

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.fr.xlf
> Add and Improve French Translation

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.it.xlf
Traduzione italiana aggiornata. @ST-Apps Vorrei inoltre far notare un dettaglio nella versione inglese "Catch Legend Pokémon" non dovrebbe essere "Catch Legendary Pokémon"?
> Aggiornato il file PokemonGo-UWP.it.xlf 

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.nl.xlf
Change a lot of sentences. Walked them throught and changed them to a more logical replacement.
> Fix and update Dutch translations

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.es-MX.xlf
New changes and a few fixes to make it more Latin American focused. Thanks to #773 @alecamaracm for his contribution which helped me figure out some of these.
#604
> Update to es-MX Translation

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.es.xlf
New strings translated and some older ones improved
> Update ES translation

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.de.xlf
Edit: During translation I saw some attacks that are twice in the database. Is this an error or do you know about that? Like "Vine Whip", "Steel Wing", "Low Kick", "Bullet Punch", Quick Attack" and some more. And I don't mean the fast attacks. The names are completely the same.
Link #604
> Translation complete: PokemonGo-UWP.de.xlf German / Deutsch

- PokemonGo-UWP/App.xaml
- PokemonGo-UWP/Entities/ItemDataWrapper.cs
- PokemonGo-UWP/PokemonGo-UWP.csproj
- PokemonGo-UWP/Utils/Game/Converters.cs
- PokemonGo-UWP/ViewModels/GameMapPageViewModel.cs
- PokemonGo-UWP/ViewModels/ItemsInventoryPageViewModel.cs
- PokemonGo-UWP/Views/GameMapPage.xaml
- PokemonGo-UWP/Views/ItemsInventoryPage.xaml
- PokemonGo-UWP/Views/ItemsInventoryPage.xaml.cs
- PokemonGo-UWP/Views/SearchPokestopPage.xaml
Added Basic Items Inventory Page.
> Basic ItemsInventory Page.

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.zh-TW.xlf
> zh-TW translation update

- PokemonGo-UWP/ViewModels/PokemonInventoryPageViewModel.cs
Fixed #731
It should now sort like the offical app.
> Fixed Sort Order in Pokemoninventory

- README.md
> Removed messy text from ReadMe

- PokemonGo-UWP/Views/PlayerProfilePage.xaml
#Fixes:
- #837 
#Changes:
- TextWrapping set to "WrapWholeWords"
> TextWrapping for achievement titles

- PokemonGo-UWP/Entities/FortDataWrapper.cs
- PokemonGo-UWP/Utils/Game/Converters.cs
- PokemonGo-UWP/Utils/Game/FortDataStatus.cs
#Fixes:
#148
#Changes:
Added flag for lured pokestops, filling that flag and changed appropriate converter
Missing PNGs, so please hold on with merge
> Pokestops with Lure

- PokemonGo-UWP/Entities/FortDataWrapper.cs
- PokemonGo-UWP/Utils/Game/Converters.cs
- PokemonGo-UWP/Utils/Game/FortDataStatus.cs
> Revert "Pokestops with Lure"

- PokemonGo-UWP/PokemonGo-UWP.csproj
- PokemonGo-UWP/Utils/GameClient.cs
- PokemonGo-UWP/Utils/Helpers/DispatcherHelper.cs
#Fixes:
Possible fix for #884 
#Changes:
Dispatcher timer operations (as well as other things) should run in dispatcher thread, but DoLogout is called also from ExceptionHandler, what could be another thread
> Dispatcher timer operations should run in dispatcher thread

- PokemonGo-UWP/Controls/CircularProgressBar.xaml.cs
- PokemonGo-UWP/PokemonGo-UWP.csproj
- PokemonGo-UWP/Utils/Achievements/AchievementValueAttribute.cs
- PokemonGo-UWP/Utils/Achievements/BronzeAttribute.cs
- PokemonGo-UWP/Utils/Achievements/GoldAttribute.cs
- PokemonGo-UWP/Utils/Achievements/SilverAttribute.cs
- PokemonGo-UWP/Utils/Game/Converters.cs
- PokemonGo-UWP/Views/PlayerProfilePage.xaml
- Fixed how badge is show
- Fixed the size of text progress
- Fixed the progress circle display
In example below we can see that first achievement doest now show properly, because the progress bar is full, and the text size is to big.
Before Fix| After fix
---|---
> Fixed achievements in profile view

- PokemonGo-UWP/Styles/Custom.xaml
- PokemonGo-UWP/Views/PlayerProfilePage.xaml
#Fixes:
- Styles
#Changes:
- UI more consistent with the other sections of the app
> Player Profile

- PokemonGo-UWP/Views/GameMapPage.xaml
- PokemonGo-UWP/Views/GameMapPage.xaml.cs
#Changes:
- The center button is now automatically shown when the user changes the view of the map manually.
> Center button is now shown when the user moves the map manually

- PokemonGo-UWP/PokemonGo-UWP.csproj
#Fixes:
Added assets from #980 to the project file.
I forgot to add the assets to the project file. Sorry.
> Fix: Added references for achievment assets to project

- .github/PULL_REQUEST_TEMPLATE.md
> ![Imgur](http://i.imgur.com/khpvWMA.png)
> -----------------------
> ![Imgur](http://i.imgur.com/Xb75NjE.png)
> -----------------------
> Fixed Pull Request Template

- PokemonGo-UWP/Utils/GameClient.cs
- PokemonGo-UWP/Utils/Signature/DeviceInfos.cs
- PokemonGoAPI/ClassDiagram1.cd
#Changes:
Its first episode of 'make 100% same communication as original client' series. This one collects location data every second and send them in next request - same behaviour as original client.
> Collecting location data every second

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.it.xlf
#Changes:
- "Cattura pokémon leggendari"
Ritradotta la stringa relativa ai pokémon leggendari
> Piccolo aggiornamento a PokemonGo-UWP.it.xlf

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.hu.xlf
#Fixes:
#Changes:
- Almost every word translated to hungarian language
- Some translations are based on MineSlash's translation
> Hungarian translation added

- PokemonGo-UWP/App.xaml
- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.de.xlf
- PokemonGo-UWP/Strings/en-US/CodeResources.resw
- PokemonGo-UWP/Utils/Game/Converters.cs
- PokemonGo-UWP/Views/PokemonInventoryPage.xaml
#Changes:
- Added translations for PokemonInventory Sorting modes in en and de.
> Added translation for sorting modes in PokemonInventory

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.nb-NO.xlf
- Added Norwegian translations
- All pokemoves translations is missing
- Berries and potion translations is missing
> Added Norwegian translation for PoGo-UWP (WIP)

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.fr.xlf
#Fixes:
#932 
#Changes:
Removed some new lines that were masking the HP bar in french of Ptitard and Rattatac (and making the textbox for the pokemon in CatchMenuScreen bigger than expected).
> removed some new line errors in FR translation

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.tr.xlf
- Removed Turkish "fast" from moves that got "fast" removed in English version
- New strings translated
> Turkish translation completely updated

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.it.xlf
N/A
- Updated Italian translation
Checked against the original app.
My first PR, is everything alright?
> Updated translation (Italian)

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.de.xlf
- Fireblast -> Feuersturm
- Karate Chop -> Karateschlag
- Mud Shot  -> Lehmschuss
Some attacks had the wrong translation
> Fixed false Attacks in German language file

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.es.xlf
- Slightly improved some translations.
- Translated Incubators, Pokémon types and sorting options strings.
- Corrected from official app.
> Updated Spanish translation

- PokemonGo-UWP/Utils/Game/Converters.cs
- #1048 
- Moved test for gold achievement in front of test for silver achievement.
> Bronze badges being displayed as silver badges

- PokemonGo-UWP/PokemonGo-UWP.csproj
- missing mp3 files, cannot star app with music option
- add reference to existing mp3 files
> add missing mp3 files to solution

- PokemonGo-UWP/ViewModels/SettingsPageViewModel.cs
- PokemonGo-UWP/Views/SettingsPage.xaml
Related to #641 and #1007
- Added Combobox to Settingspage
- Added Handling to the Viewmodel
Maybe there is a better way to get all available languages, but for now ith should work.
> Ingame language selection

- PokemonGo-UWP/ViewModels/CapturePokemonPageViewModel.cs
- Fixed Exception, if user has no Pokeballs in Capture view
> Fixed: NPE, if user has no Pokeballs in Capture view

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.el.xlf
- Updated the translations
- Translated the new values
Other: okay @ST-Apps you can merge now
> Greek Translations PokemonGo-UWP.el.xlf

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.zh-TW.xlf
Update zh-TW translation
pokemontype and missing translation files
> Update zh-TW translation

- PokemonGo-UWP/Entities/IMapPokemon.cs
- PokemonGo-UWP/Entities/LuredPokemon.cs
- PokemonGo-UWP/Entities/MapPokemonWrapper.cs
- PokemonGo-UWP/Entities/NearbyPokemonWrapper.cs
- PokemonGo-UWP/PokemonGo-UWP.csproj
- PokemonGo-UWP/Utils/GameClient.cs
- PokemonGo-UWP/ViewModels/CapturePokemonPageViewModel.cs
- PokemonGo-UWP/ViewModels/GameMapPageViewModel.cs
- PokemonGo-UWP/ViewModels/PokemonDetailsPageViewModel.cs
- PokemonGo-UWP/Views/GameMapPage.xaml
- PokemonGo-UWP/Views/ItemsInventoryPage.xaml
- PokemonGo-UWP/Views/PokemonDetailPage.xaml
- PokemonGo-UWP/Views/PokemonDetailPage.xaml.cs
- Integrated ItemsInventoryPage provided by @OliverRM see #1040 
Ask Author for more information
> Updated ItemsInventoryPage

- PokemonGo-UWP/ViewModels/CapturePokemonPageViewModel.cs
- PokemonGo-UWP/Views/CapturePokemonPage.xaml.cs
- #888 
- #845 
- #755
- #740 
- #1013
- Decoupled ```SelectedCaptureItem``` from FindingPokeballs
- Refactored Finding pokeballs to ```SelectAvailablePokeBall``` and ```SelectPokeballType```
- Fixed throwing berries
- Fixed reusing pokeballs (previous fix was giving exceptions)
- For berries I had to make last throwed ItemId in ViewModel and check it after throw in View to reset its position for pokebal to throw again
> Fix using of berries, reusing pokeballs and exception

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.cs.xlf
- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.de-CH.xlf
- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.de.xlf
- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.el.xlf
- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.es.xlf
- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.fi.xlf
- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.fr.xlf
- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.hr-HR.xlf
- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.hr.xlf
- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.hu.xlf
- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.id.xlf
- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.it.xlf
- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.ja.xlf
- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.nb-NO.xlf
- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.nl.xlf
- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.nn-NO.xlf
- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.pl.xlf
- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.pt-BR.xlf
- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.pt-PT.xlf
- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.ru.xlf
- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.sk.xlf
- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.tr.xlf
- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.zh-CN.xlf
- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.zh-HK.xlf
- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.zh-TW.xlf
- PokemonGo-UWP/Strings/en-US/Items.resw
- PokemonGo-UWP/Strings/nb-NO/Items.resw
- PokemonGo-UWP/Strings/pt-PT/Items.resw
- PokemonGo-UWP/Strings/zh-TW/Items.resw
- Renamed "Incense Cool" to "Cool Incense"
- Renamed "Incense Floral" to "Floral Incense"
- Renamed "Incense Spicy" to "Spicy Incense"
- Renamed "Incubator Basic" to "Incubator"
- Renamed "Incubator Basic Unlimited" to "∞ Incubator"
- Renamed "Troy Disk" to "Lure Module"
> Fixed Items Names & Resources

- PokemonGo-UWP/Views/PokemonInventoryPage.xaml
Added forgotten x:uid in #1129
> Fixed localisation of PokemoninventoryPage pivot headers

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.de-CH.xlf
- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.de.xlf
- PokemonGo-UWP/Strings/en-US/Achievements.resw
The youngster achievement is not "catch X rattata", it's "catch X small rattata". (SMALL!)
en-US resw-File 
de and de-CH XLF Files
>  Fixed youngster achievement description  (en-US, de, de-CH)

- PokemonGoAPI/Rpc/BaseRpc.cs
["I must've put a decimal point in the wrong place or something. Shit, I always do that. I always mess up some mundane detail."](http://gotwavs.com/php/sounds/?id=gog&media=MP3S&type=Movies&movie=Office_Space&quote=mundanedetail.txt&file=mundanedetail.mp3)
> Fixed a bug in BaseRpc.cs

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.pt-BR.xlf
Compile fix
Removed duplicated id in PokemonGo-UWP.pt-BR.xlf
> compile fix

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.nb-NO.xlf.xlf
- Fixed Incubator strings
- Fixed some misspellings
- Improved some translations
- Made some translations final version
> Updated nb-NO translations

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.it.xlf
> Update PokemonGo-UWP.it.xlf (italian translation)

- PokemonGo-UWP/Strings/en-US/Items.resw
- No fixes
- Added Razz Berry description
- Added Lucky Egg description
- Added Super Potion description
- Added Lure Module (Troy Disk) description
- Added Camera description
- Changed descriptions for Incubator Basic & Unlimited (To use original apps description)
- Added Unknown item description
- Added above descriptions to en-US strings only
- No other languages done
> Added some more item descriptions

- PokemonGo-UWP/Utils/GameClient.cs
- Adds a case to put in egg hatching video easily 
- Game Client now check for hatching eggs
Recieves information but doesn't do anything with it (I believe we should add a page for hatching and just run the evolving storyboard from egg to pokemon
> Show Eggs Hatching

- PokemonGo-UWP/Styles/Custom.xaml
- PokemonGo-UWP/Views/SettingsPage.xaml
- Fixed live tile buttons
- Removed MEGA-GRID
- Fix the UI (Margins)
- Add ComboBox Style
> New UI for SettingsPage

- PokemonGo-UWP/Utils/Extensions/RandomExtensions.cs
- PokemonGo-UWP/Utils/Signature/DeviceInfos.cs
- PokemonGo-UWP/Utils/Signature/DeviceInfosAndroid.cs
- PokemonGo-UWP/Utils/Signature/DeviceInfosIOS.cs
- PokemonGoAPI/Helpers/IDeviceInfos.cs
- PokemonGoAPI/Helpers/RequestBuilder.cs
- PokemonGoAPI/Helpers/Vector.cs
- PokemonGoAPI/Proto/Networking/Envelopes/Signature.cs
- fixed generating iPhone device ID - its 16 bytes, not 20 
- fixed filling activity info + other sensor values
- Added exact device info from iPhone
> Improved iPhone spoofing

- PokemonGo-UWP/App.xaml.cs
- PokemonGo-UWP/Utils/Helpers/ExceptionHandler.cs
- PokemonGoAPI/Enums/StatusCode.cs
- PokemonGoAPI/Exceptions/AccountLockedException.cs
- PokemonGoAPI/Exceptions/ApiNonRecoverableException.cs
- PokemonGoAPI/PokemonGoAPI.csproj
- PokemonGoAPI/Rpc/Download.cs
- PokemonGoAPI/Rpc/Login.cs
- PokemonGoAPI/Rpc/Map.cs
- PokemonGoAPI/Session/ApiFailureStrategy.cs
- Fixed using non strong typed class names in exception handler
- Removed unnecessary messages in initial request
- Filling download hash with real data (not wrong constant)
- Added StatusCode  enum
- Added AccountLockedException (throws when StatusCode = 3)
> Added banned account detection + some other fixes in response/exceptions handling

- PokemonGo-UWP/Utils/Game/DataTemplateSelectors.cs
- PokemonGo-UWP/ViewModels/PokedexPageViewModel.cs
- PokemonGo-UWP/Views/PokedexPage.xaml
- Pokedex now lists pokemon to the last pokemon seen/captured
- Pokemon seen but not captured now are gray and can't see all information
Reference #940 #1204
> Pokedex improvements

- PokemonGo-UWP/Utils/Helpers/ExceptionHandler.cs
- Remove ApiHandledException which is not used
- Change Relogin debug text
> Cleanup after relogin fix from #1214

- PokemonGo-UWP/Strings/en-US/Items.resw
- Fixed Great, Ultra and Master Ball descriptions
- Added Great, Ultra and Master Ball descriptions
- Added more berry descriptions (Using Razz Berry Description)
- Only made for en-US
- Will try to do translations if needed
> Add more descriptions (en-US)

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.da.xlf
> Add Danich Translation

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.it.xlf
Almost complete, just 4 strings missing
> Update Italian translation

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.de.xlf
- Translated the new introduced strings for the german locale
The resources are somewhat of a mess there is a "Seen" and a "Seen:" in it. We should only have this once inside the resources. Need to refactor.
> Updated german translation

- PokemonGo-UWP/App.xaml.cs
- PokemonGo-UWP/Entities/VersionInfo.cs
- PokemonGo-UWP/Package.appxmanifest
- PokemonGo-UWP/PokemonGo-UWP.csproj
- PokemonGo-UWP/Utils/Game/UpdateManager.cs
Closes issues
-------------
Changes
-------
- Uses control file at https://raw.githubusercontent.com/PoGo-Devs/PoGo/master/version.json
- Allows to send optional update (newest version > installed version), forced update (min version >= newest version > installed version) , ban old version when there is no update yet (min version > newest version)
- Needs internet connection for app start
- Please review this because I already sleep :)
Change details
--------------
TODO: connect it with filling unknown & version number to API (can be implemented later, currently using constant)
TODO: move strings to resources and translate them
TODO: version.json must be adjusted tu real release URL and versions
> new update system

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.en-GB.xlf
> Added en-GB translation

- PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.hr-HR.xlf
Changes
-------
- Change 1
Started translating hr-HR
Change details
--------------
-----------------
I may finish it tomorrow, but not sure if ill have time
> started hr-HR translatio

- PokemonGo-UWP/Utils/Signature/DeviceInfosAndroid.cs
- PokemonGo-UWP/Utils/Signature/DeviceInfosIOS.cs
- PokemonGoAPI/Helpers/IDeviceInfos.cs
- PokemonGoAPI/Helpers/RequestBuilder.cs
- PokemonGoAPI/Proto/Networking/Envelopes/Signature.cs
Updates from https://github.com/AeonLucid/POGOProtos/pull/214:
- Altitiude was # 4,
- Speed was # 18
- Unknown20 is now Course.
TODO: @wally, Speed needs to be wired up through the signature. I just stubbed out the property manually.
> Signature updates

- PokemonGoAPI/Exceptions/LoginFailedException.cs
- PokemonGoAPI/Interfaces/IApiFailureStrategy.cs
- PokemonGoAPI/Login/GoogleLogin.cs
- PokemonGoAPI/Login/ILoginType.cs
- PokemonGoAPI/Login/PtcAuthenticationTicketResponse.cs
- PokemonGoAPI/Login/PtcLogin.cs
- PokemonGoAPI/Login/PtcLoginParameters.cs
- PokemonGoAPI/PokemonGoAPI.csproj
- PokemonGoAPI/Session/AccessToken.cs
- Documented AccessToken.cs
- Added new `ExpiresUtc` property (to be more descriptive) and added compatibility for old `Expiry` property.
- Properly implemented Async for PtcLogin.cs
- Cleaned up dead code in PtcLogin.cs
- Improved names and error handling.
> Clean Up PtcLogin

- PokemonGo-UWP/Utils/Achievements/AchievementType.cs
Closes issues
-------------
- #1420 
Changes
-------
- Kanto Gold Achievement level from 200 to 100
Change details
--------------
> Kanto Gold Achievement level

- README.md
Changes
-------
- Updated link to releases in changelog
Change details
--------------
The link to the releases in changelog still linked to RC1. It now links to the list of releases instead.
> Updating link to recent releases in README.md

- PokemonGo-UWP/PokemonGo-UWP.csproj
- PokemonGo-UWP/Views/SettingsPage.xaml
Closes issues
-----
- Closes #1433
Changes
-----
- Added application version in the settings page under Logout
Screenshot
-----
> Added application version in the settings page

- PokemonGo-UWP/Views/SettingsPage.xaml
Changes
-------
- Fixed UI Bug with Language ComboBox in SettingsPage
Change details
It's only a Little fix in one file.
> Fixed UI Bug with Language ComboBox in SettingsPage

- PokemonGo-UWP/Utils/Signature/DeviceInfosIOS.cs
- PokemonGoAPI/Helpers/Utils.cs
- PokemonGoAPI/Login/GSPOAuthSharp.cs
- PokemonGoAPI/Login/PtcLogin.cs
- PokemonGoAPI/Rpc/Login.cs
- This PR fixes issue #1510.
- Also adds the CheckChallenge request on login.
WIP. Do not merge yet.
> HttpClient, Hash, and LoginRequest fixes

- PokemonGo-UWP/App.xaml
- PokemonGo-UWP/Utils/Game/Converters.cs
- PokemonGo-UWP/Utils/Game/DataTemplateSelectors.cs
- PokemonGo-UWP/ViewModels/PokedexPageViewModel.cs
- PokemonGo-UWP/Views/PokedexPage.xaml
- PokemonGo-UWP/Views/PokedexPage.xaml.cs
Changes
-------
- Implemented #1502 after being overwritten by #1537
- Removed unused code
- Changed the PokedexPageViewModel to work with PokemonId instead of more complex KeyValuePairs
> Reimplemented #1502 and additional fixes/cleanup in PokedexPage

- PokemonGo-UWP/Entities/VersionInfo.cs
- PokemonGo-UWP/PokemonGo-UWP.csproj
- PokemonGo-UWP/Utils/Game/UpdateManager.cs
- PokemonGo-UWP/Utils/Signature/DeviceInfoBase.cs
- PokemonGo-UWP/Utils/Signature/DeviceInfosAndroid.cs
- PokemonGo-UWP/Utils/Signature/DeviceInfosIOS.cs
- PokemonGo-UWP/Utils/Signature/IDeviceInfoExtended.cs
- PokemonGoAPI/Helpers/IDeviceInfos.cs
- PokemonGoAPI/Helpers/RequestBuilder.cs
- PokemonGoAPI/Helpers/Utils.cs
Changes
-------
- Some magic values are now read from version.json instead of hardcoded constants. So when there will be some change in these values, we have not release new version
@robertmclaws Please can you merged it to 2.0? Thanks
> wired version.json variables to API

- PokemonGo-UWP/ViewModels/LoginPageViewModel.cs
- PokemonGoAPI/Exceptions/LoginFailedException.cs
- PokemonGoAPI/Login/PtcAuthenticationTicketResponse.cs
- PokemonGoAPI/Login/PtcLogin.cs
- PokemonGoAPI/Login/PtcLoginParameters.cs
- Adjustments to the code and logic to handle the response from the server when an account needs to be activated.
- Adjustments to track when we encounter a response from the PTC Login servers that we haven't seen before.
> Make PtcLogin handle account activation

- PokemonGo-UWP/ViewModels/PlayerProfileViewModel.cs
- PokemonGo-UWP/ViewModels/PokedexPageViewModel.cs
- PokemonGo-UWP/ViewModels/SearchPokeStopPageViewModel.cs
Changes
-------
- When **Count** were used to check if the enumerable had elements, changed to **Any** and **All**.
- Created a helper method for summing the ItemAward items.
> Correcting simple LINQ misuses

- Google.Protobuf/Google.Protobuf.csproj
- PokemonGo-UWP.Tests/PokemonGo-UWP.Tests.csproj
- PokemonGoAPI/PokemonGoAPI.csproj
-    <TargetPlatformVersion>10.0.10586.0</TargetPlatformVersion>
+    <TargetPlatformVersion>10.0.14393.0</TargetPlatformVersion>
> Retarget platform to 10.0.14393

- PokemonGo-UWP/App.xaml.cs
- PokemonGo-UWP/Utils/GameClient.cs
- PokemonGo-UWP/ViewModels/AchievementDetailPageViewModel.cs
Closes issues
-------------
- Closes #1613 
Changes
-------
- Refactored some classes
> #1613 Refactored some classes

- PokemonGo-UWP/project.json
HockeySDK -> 4.1.4
Octokit -> 0.22.0
UniversalMapControl -> 0.3.45
XamlAnimatedGif -> 1.1.5
> Update NuGet packages

- PokemonGo-UWP/Utils/Helpers/ExceptionHandler.cs
- PokemonGo-UWP/Utils/Settings/SettingsService.cs
- PokemonGo-UWP/ViewModels/SettingsPageViewModel.cs
- PokemonGo-UWP/Views/GameMapPage.xaml.cs
- PokemonGo-UWP/Views/SettingsPage.xaml
- PokemonGo-UWP/Views/SettingsPage.xaml.cs
Closes issues
-------------
- Closes : when navigating to settings page, then back to map page, sometimes map is not moving anymore
Changes
-------
- added 3DView to map page
- cleanup in settings view to have list of "rotation mode" based on enum instead of hardcoded list
- added a "debug" settings to display exception details (allow to have message and inner exception message even in release mode)
Change details
--------------
N/A
N/A
> Fix for map and more stuff

- PokemonGo-UWP/Views/GameMapPage.xaml.cs
Closes issues
-------------
- Closes #1664
Changes
-------
- N/A
Change details
--------------
N/A
N/A
> Gps rotation fix

- PokemonGoAPI/Helpers/Crypt/PCrypt.cs
Closes issues
-------------
None
Changes
-------
See title
Change details
--------------
Not very important for us, because decryption is not currently used
> Small fix in PCrypt decryption for payloads > 256 (by turnt)

- PokemonGo-UWP/project.json
- PokemonGoAPI/Extensions/CookieContainerExtensions.cs
- PokemonGoAPI/Login/PtcLogin.cs
Closes issues
-------------
#1782, #1783, #1790, #1792
> Temporary fix for cookie problems

- PokemonGo-UWP/Utils/GameClient.cs
- PokemonGo-UWP/ViewModels/PokemonDetailPageViewModel.cs
- PokemonGo-UWP/ViewModels/PokemonInventoryPageViewModel.cs
- PokemonGo-UWP/Views/Pokemon/EggDetailControl.xaml.cs
- PokemonGo-UWP/Views/Pokemon/EggDetailPage.xaml
- PokemonGo-UWP/Views/Pokemon/EggInventoryControl.xaml
- PokemonGo-UWP/Views/Pokemon/PokemonInventoryControl.xaml
- Closes #1724
- Closes #1728
- Closes #1729 
Not able to test all the fixes (no account with free incubators).
@BadiBasso you might want to test these before we merge and close.
> Fixing multiple bugs in Pokemon section

- PokemonGo-UWP/App.xaml.cs
- PokemonGo-UWP/Strings/en-US/Resources.resw
Hopefully these changes make the warnings a bit easier to understand.
> Login and banning text clarifications.

- PokemonGo-UWP/Package.appxmanifest
- PokemonGoAPI/Helpers/Crypt/NiaHash.cs
Closes issues
-------------
Changes
-------
Constants from 1.15.0 version
Change details
--------------
> constants updated to version 0.45.0/1.15.0

- PokemonGo-UWP/App.xaml.cs
Explaining more about the situation to try to prevent people from open time-wasting GitHub Issues. Probably won't matter though.
> Improving the app lockout text.
