PokemonGo-UWP/Views/GameMapPage.xaml

This change will correct the Pokestops anchorpoints and they will no longer 'float' across the map.

Pokestops anchorpoint

---

PokemonGo-UWP/App.xaml.cs

Application will start now in full screen mode, but user can still open bottom navigation bar.

Hidden botton NavigationBar on start

---

PokemonGo-UWP/ViewModels/GameMapPageViewModel.cs
PokemonGo-UWP/Views/GameMapPage.xaml

I also noticed (like in issue #297) that the experience bar was not displayed correctly. The reason is that the maximum of the progressbar was set to the **full amount** of experience that was needed for the next level.
My first approach was to set the minimum value to the amount of experience from the previous level, but than the progressbar would be filled all the time. Now I calculated a value between 0 and 100 that represents the right percentage value.

Fixed wrong displaying of experience

---

PokemonGo-UWP/Strings/ja-JP/Pokemon.resw

Added:
1. ja-JP Pokemon Names.
Fixed:
Nothing.

[ja-JP] Pokemon Translate 

---

PokemonGo-UWP/Utils/UpdateManager.cs

Currently, there will be thrown an IOException, if the "Updates" Folder is not available. Then it will be create.
With the new Change, the "updates" Folder will be created, but if it exists, it will be opened.

Fixed getting "Updates" folder

---

PokemonGo-UWP/Views/PokemonInventoryPage.xaml

This mimics the behavior of the official app.
I have simply reused the hide storyboard on every item click. Since there are no disabled items this should suffice.

Automatically close the pokemon SortMenuPanel when a sorting is selected

---

PokemonGo-UWP/App.xaml.cs
PokemonGo-UWP/PokemonGo-UWP.csproj
PokemonGo-UWP/Utils/AsyncSynchronisationContext.cs

AsyncSynchronizationContext let catch exceptions from async void methods
(UI methods from events) before it crashes the app.

Prevent exceptions thrown from async void methods from bringing down the application

---

PokemonGo-UWP/Strings/en-US/Resources.resw
PokemonGo-UWP/Utils/SettingsService.cs
PokemonGo-UWP/ViewModels/SettingsPageViewModel.cs
PokemonGo-UWP/Views/GameMapPage.xaml.cs
PokemonGo-UWP/Views/SettingsPage.xaml

- Fix for #587.
- Better naming for the "MapZoomEnabled" setting.
- Fix for #586.
- Minor translation fix ("Pokemon" is both singular and plural, should never have an "s" at the end.)

Remember Map Zoom Fixes

---

.gitignore
PokemonGo-UWP/App.xaml.cs
PokemonGo-UWP/Utils/GameClient.cs
PokemonGo-UWP/ViewModels/CapturePokemonPageViewModel.cs
PokemonGo-UWP/Views/CapturePokemonPage.xaml.cs

- Central place to change the update timer if Ninantic ever goes back to
5 second refresh intervals.
- Remove Pokemon from the `GameClient.NearbyPokemon` ObservableCollection when they
are caught or flee.
- .gitignore updates.
(PS, LOVE the refactor. Code is much cleaner now.)

Remove NearbyPokemon when Caught or Fled

---

PokemonGo-UWP/App.xaml.cs

Previous implementation ``` new DisplayRequest().RequestActive(); ``` didn't work.
Here I read, that it can't be local variable, but global for it to persist:
http://stackoverflow.com/questions/25251094/stopping-screen-timingout-windows-phone-8-1

Fix #624 - Previous imp. didn't work

---

PokemonGo-UWP/ViewModels/LoginPageViewModel.cs

I was checking the responses from login requests and maybe this can be nice to add. I have checked with the official app and they are the same apparently. I don't like too much the try-catch but I put it just in case something change from the server side. I am not very familiar with C# so improvements are welcome :)
This is how it looks like:

Added LoginFailedException message from http response

---

PokemonGo-UWP/ViewModels/PokemonDetailsPageViewModel.cs

Instead of current pokemon name.
Not the most elegant way, just copied from the converter.

fixed "got a *** Candy.." message to display pokemon familiy name

---

PokemonGo-UWP/App.xaml.cs
PokemonGo-UWP/Entities/FortDataWrapper.cs
PokemonGo-UWP/Entities/MapPokemonWrapper.cs
PokemonGo-UWP/Utils/GameClient.cs
PokemonGo-UWP/Utils/Helpers/ExceptionHandler.cs
PokemonGo-UWP/ViewModels/CapturePokemonPageViewModel.cs
PokemonGo-UWP/ViewModels/GameMapPageViewModel.cs
PokemonGo-UWP/ViewModels/SearchPokeStopPageViewModel.cs
PokemonGo-UWP/Views/PlayerProfilePage.xaml.cs

- Fix #645 by Logouting, auto-loging in again and completely reinicializing GameMapPage.
- Add Exception message propagation from App_UnhandledException.
- Change void to Task at ToggleUpdateTimer and fix all usages to await.
- Add link to GameMapPageViewModel into GameClient -> needs refactoring.
- Temporary fix for compilation error at PlayerProfilePage.xaml.cs:13
@ST-Apps Please revise the code before merging.
I tested it few times and it should work without any user interaction after those 30mins.

Fix #645; Enhance exception handling and async update timer;

---

PokemonGo-UWP/Utils/GameClient.cs

#Fixes:
- No known issues associated 
#Changes:
- Add 3 empty NearbyPokemons at startup
- Add null check for _client in _geolocator.PositionChanged
- Without those 3 empty pokemons the GameMapPage was Binding indexes 0-2 to empty array, which gave errors, but worked afterwards. Now it's without errors.
- Without null check for _client it was throwing null in some cases.

Fix errors from output window

---

PokemonGo-UWP/Views/GameMapPage.xaml

I found this while browsing the code, I don't know if it will change anything since this border name is not referenced but it's still better to have it with the right name.

Tiny typo error fix in GameMapPage

---

PokemonGo-UWP/Utils/Game/Converters.cs

#Fixes:
-
#Changes:
- Changed team colors in Converters.cs to the actual colors from the original game. 
The colors are defined as a ARGB using Color.FromArgb. The alpha values are set to 255 in order to create a solid color.
Color values courtesy of eamax from Discord.

Change team colours

---

PokemonGo-UWP/Views/GameMapPage.xaml

Fixing #8b7d615 to remove the border name. The fix provided in that checkin duplicated an existing XAML name.

FIX: Broken build

---

PokemonGo-UWP/Strings/en-US/CodeResources.resw

#Changes:
- Changed "Catch Legendary Pokémon"
Before it was written "Catch Legend Pokémon" that's incorrect

Corrected CodeResources.resw (en-US)

---

PokemonGo-UWP/ViewModels/CapturePokemonPageViewModel.cs
PokemonGo-UWP/ViewModels/EggDetailPageViewModel.cs
PokemonGo-UWP/ViewModels/GameMapPageViewModel.cs
PokemonGo-UWP/ViewModels/ItemsInventoryPageViewModel.cs
PokemonGo-UWP/ViewModels/PlayerProfileViewModel.cs
PokemonGo-UWP/ViewModels/PokemonDetailsPageViewModel.cs
PokemonGo-UWP/ViewModels/PokemonInventoryPageViewModel.cs
PokemonGo-UWP/ViewModels/SearchPokeStopPageViewModel.cs

#Fixes:
- Possible fix for #789 and #791
#Changes:
- Fix serialization of PlayerProfile and PlayerStats
- Serialization didn't work, because ```IDictionary<string, object> suspensionState``` can only save types implementing IPropertySet. So I changed it to use Json serialization/deserialization

Fix suspension serialization

---

PokemonGo-UWP/Entities/FortDataWrapper.cs
PokemonGo-UWP/Utils/Game/Converters.cs
PokemonGo-UWP/Utils/Helpers/GeoHelper.cs
PokemonGo-UWP/project.json

I was having problems with GeoExtensions, that I could not even compile the project, so I made this "helper" to not depend of GeoExtensions.
It is a really necessary and vital change? No, but it's not a bad change.
The GeoHelper does exactly the same job, returning the same result in meters.
The GeoExtensions package is almost non used, and has a lot of unnecessary thing to PoGo.

Replacing GeoExtensions to GeoHelper

---

PokemonGo-UWP/Views/PlayerProfilePage.xaml

#Fixes:
- Aligned achievement titles
#Changes:
- N/A
The titles for achievements were misaligning the whole achievement depending on the length of the title.

Aligned Achievement Titles

---

PokemonGo-UWP/Styles/Custom.xaml
PokemonGo-UWP/Utils/Game/Converters.cs
PokemonGo-UWP/Utils/GameClient.cs
PokemonGo-UWP/ViewModels/GameMapPageViewModel.cs
PokemonGo-UWP/Views/GameMapPage.xaml
PokemonGo-UWP/Views/SettingsPage.xaml

- Adjusted the converter logic to tweak visibility instead of styles.
- Changed the PokedexInventory collection to ObservableCollectionPlus, so that the CollectionChanged event could be handled to re-fire the Converters. (Handles https://github.com/ST-Apps/PoGo-UWP/pull/926#issuecomment-240239714)
- Fixed the layout for the "NearbyPokemon" window in the bottom corner of the map, so it will show more Pokemon on PCs and Tablets.
- Fixed a stupid bug in the Settings page where I overlapped checkboxes by mistake.

Nearby + Pokedex Fixes

---

PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.cs.xlf
PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.de.xlf
PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.el.xlf
PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.es.xlf
PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.fi.xlf
PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.fr.xlf
PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.hu.xlf
PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.id.xlf
PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.it.xlf
PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.ja.xlf
PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.nl.xlf
PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.pl.xlf
PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.pt-BR.xlf
PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.pt-PT.xlf
PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.ru.xlf
PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.sk.xlf
PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.tr.xlf
PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.zh-CN.xlf
PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.zh-HK.xlf
PokemonGo-UWP/MultilingualResources/PokemonGo-UWP.zh-TW.xlf
PokemonGo-UWP/Strings/de/Resources.resw
PokemonGo-UWP/Strings/en-US/Resources.resw
PokemonGo-UWP/Views/EggDetailPage.xaml

**#Fixes:**
- Added word wrap to detail text
**#Changes:**
- Created resources for detail text and button text
- Added German translation
**#Other informations:**
See #604
I'm not sure, if the string "km" is "mi" in the US version and should be put into the resource file, too. Maybe, someone with a US version on Android or iPhone could check this. If it's "mi", what happens to the numbers? What has to be displayed for 2km, 5km and 10km instead? And this could be an issue also regarding the distance one has already walked.

Localized EggDetailPage and added German translation. #604

---

PokemonGo-UWP/App.xaml
PokemonGo-UWP/PokemonGo-UWP.csproj
PokemonGo-UWP/Strings/en-US/PokemonTypes.resw
PokemonGo-UWP/Utils/Game/Converters.cs
PokemonGo-UWP/Utils/Game/Resources.cs
PokemonGo-UWP/Views/PokemonDetailPage.xaml

- Implemented Internationalization of pokemon types
- Created converter for PokemonType Enum->Translated String
- Integrated converter in PokemonDetailsPage
- Added en-US resw file for pokemon types (PokemonTypes.resw)
I didn't include any xlf files in the commit/PR as this would most certainly conflict with a shitload of other PRs. But you can generate und commit them yourself after accepting the PR to circumvent any conflicts. Will commit the german translation when this PR is merged.
Oh yeah and I know this PR is even conflicting with one of my own branches waiting for merge. Let me see which one you accept first and then I'll resolve the conflict in the other one. ;)

Added support for internationalization/translation of pokemon types

---

PokemonGo-UWP/Utils/GameClient.cs
PokemonGo-UWP/ViewModels/LoginPageViewModel.cs
PokemonGoAPI/Login/PtcLogin.cs

N/A (or not found any)
- Add correct exception handling when username or password is incorrect
- Add checks on DoLogout, because when "something went wrong" on login screen happens, then it tries to logout with not initialized GameClient
Previous implementation doesn't work:
```
catch (LoginFailedException e)
```
because PokemonGoAPI throws it as this:
```
throw new Exception($"Pokemon Trainer Club gave error(s): '{string.Join(",", loginResponseErrors)}'");
```
So now, I handle it like this:
```
catch (Exception e)
{
if (e.Message.Contains("Your username or password is incorrect."))
{
```
because the Message is:
```
Message = "Pokemon Trainer Club gave error(s): 'Your username or password is incorrect. You have 3 attempts left before you will be locked out of your account for 15 …
```

Fix sign in issues

---

PokemonGo-UWP/Views/PlayerProfilePage.xaml
PokemonGo-UWP/Views/PokemonDetailPage.xaml
PokemonGo-UWP/Views/PokemonInventoryPage.xaml

- Color change in profile experience progressbar according to the team color
- The way to round the progress bar in pokémon detail page
- In the detail page of pokémons, corrected a small "lack of space" when 100 candys are required to evolve
- Roundend pregressbar in profile
- Roundend pregressbar in Pokémons list

Rounded Progressbars + Fixed profile progressbar to color change according to the team color

---

PokemonGo-UWP/App.xaml
PokemonGo-UWP/Styles/Custom.xaml
PokemonGo-UWP/Utils/Game/Converters.cs
PokemonGo-UWP/Views/PokemonInventoryPage.xaml

- Show both pivot headers in pokémon inventory.
- Chaged pivo header style to better aproximate iOS app.
Pivot Headers were hardcoded into grid and the default headers were hidden in style.
Used styled default headers for the pivot instead.
Show both Pokemon and Egg headers.
Added new converter for Pivot Header Bar visibility.

PokemonInventory: Show both pivot Headers

---

PokemonGo-UWP/Views/SettingsPage.xaml
PokemonGo-UWP/Views/SettingsPage.xaml.cs

- Phones with compasses can no longer turn on compass rotate mode
- ComboBoxItem doesn't showup
Currently, on phones with no compass they crash if you select compass for auto-rotate

Compassless crash

---

PokemonGo-UWP/Styles/Custom.xaml
PokemonGo-UWP/Views/GameMapPage.xaml
PokemonGo-UWP/Views/PlayerProfilePage.xaml
PokemonGo-UWP/Views/PokemonDetailPage.xaml
PokemonGo-UWP/Views/PokemonInventoryPage.xaml

- N/A
- Changes the PlayerProfilePage.xaml experience ProgressBar style to a style similar to the official app. The style is based on [this](https://localtvwtvr.files.wordpress.com/2016/07/160729170850-sam-clark-pokemon-go-profile-exlarge-169.jpg?quality=85&strip=all&w=770&strip=all) image.
- Changes the PokemonInventoryPage.xaml and PokemonDetailPage.xaml HP ProgressBar styles to a style stimilar to the official app. The style is based on [this](http://cdn2.pcadvisor.co.uk/cmsdata/features/3625388/pokemon_go_5c.png) image of the PokemonList and [this](http://i.stack.imgur.com/lfDNW.jpg) image of the PokemonDetail.
- Removed properties which didn't do anything because they weren't bound to in the style used.
- N/A
- N/A

Styles of Pokemon HP and Player XP

---

PokemonGo-UWP/Entities/PokemonDataWrapper.cs
PokemonGo-UWP/ViewModels/PokemonInventoryPageViewModel.cs
PokemonGo-UWP/Views/PokemonInventoryPage.xaml
PokemonGo-UWP/Views/PokemonInventoryPage.xaml.cs

- Add memory for navigating back to pokelist
- First Making it via SelectedItem didn't work.
- When you navigate back from pokemon detail or from pokemon transfer, you will end up having latest place of that pokemon on the bottom of the viewable screen. So it's perfect for "Pidgey Spam".
- When you navigate from GameMap, you will end up at the top.
- When you change ordering, you will end up at the top.
- It should be bullet-proof, no crashes allowed!! :)
- I haven't tested anything else (Is there anything else regarding pokelist?)
I was drowning for 7 hours before I got the right idea, how to make it. So if it is not elegant, I would like to see you drowning for 7 hours before actually making it. :D

Add memory for navigating back to pokelist

---

PokemonGo-UWP/Views/GameMapPage.xaml

- Fix the #1067 issue: pokémon under the pokestop cannot be catched
- reordered the element of the catchablepokemon, pokestop and luredpokemon item in gamemapmage.xml
- The original idea is came from SlowSlash.
- I just made it for github project.

replace order to catchable the pokemon under the pokestop #1067

---

PokemonGo-UWP/App.xaml.cs

- We check if we have a phone to hide the status bar. Now we check if a StatusBar is available.
- Added overlay support so now the app wont resize when the user summons the Navigation bar(back button, windows button, search button)
Picture of how the app responds when we summon the Navigation bar: [Picture](http://prnt.sc/c8weaa)
-Tapping anywhere on the screen will dismiss the Navigation bar.
-The overlay support will help to display the status bar too in the near future like the official app.

Changed the way we hide the StatusBar and added overlay support

---

PokemonGo-UWP/PokemonGo-UWP.csproj
PokemonGo-UWP/Views/PokemonDetailPage.xaml

Does not contain any fixes.
Added icons to pokemon detail page context menu.

Added transfer context menu icons

---

PokemonGo-UWP/Views/PokemonDetailPage.xaml

- If Pokémon had only 1 Type instead of 2 (water instead of grass/water), the translation converter wasn't applied

Fixed missing translation for Pokémon type if it had only 1

---

PokemonGo-UWP/Package.appxmanifest
PokemonGo-UWP/Utils/GameClient.cs
PokemonGoAPI/Session/AccessToken.cs

Changes
-------
- When AccessTokenExpiredException we forcibly Expire our token if .IsExpired in DoLogin somehow fails
- IsExpired is more optimistic with 60sec precheck to eliminate wire delay and heartbeat delay
- Set current version to 29 as is released
Change details
--------------
These changes are made as a precautionary solution for ppl getting banned maybe because of login loop.

Fix possible login issues with expired token

---

PokemonGo-UWP/ViewModels/PokemonDetailsPageViewModel.cs
PokemonGoAPI/Interfaces/IApiFailureStrategy.cs

Changes
-------
- Removes transfer result MessageDialog
- Adds Busy after confirmation of Transfer, Rename and Favorite
Change details
--------------
- When transfer happened, user had to wait until `MessageDialog`, which was cumbersome after to click on. Against official app our transfer was too slow process. We should only make some quick popup text to inform user that he got candy and not make him click to confirm.
- Busy dialogs are added because server sometimes takes some time to process the request and user didn't know that. With busy, user now knows. (On rename it sometimes didn't even propagate because of this)
- I also fixed the latest commit build. There were missing using in `IApiFailureStrategy.cs`
Resources for :
- …

(Enhancement) Add Busy for PokemonDetail awaiting dialogs

---

PokemonGoAPI/Session/AccessToken.cs

Can add this back in later after everyone updates to the build that contains this fix.

Make ExpiresUtc not required for now.

---

PokemonGoAPI/Client.cs
PokemonGoAPI/Constants.cs
PokemonGoAPI/Session/ApiFailureStrategy.cs

- Check if AccessToken is null before checking if it is expired before we log in pre-request.
- Based on @wallycz analysis, change the user agent when logging in.
- Based on @wallycz analysis, wait 11 seconds before retrying on ServerOverloaded (same as official app).

Misc Fixes

---

PokemonGoAPI/Login/PtcLogin.cs

- Make each login attempt create a new instance of both the `HttpHandler` and `HttpClient`, and properly dispose of them.

Fix a bug I accidentally introduced in #1374

---

PokemonGo-UWP/ViewModels/CapturePokemonPageViewModel.cs

Change details
--------------
- Remove Busy from CatchingPage
- Remove server-side InventoryUpdate and replace it with local descreasing of thrown items
- Disabled wrong state after catching
- Removed 5s wait when missed
- Wrong state was, when you catch pokemon, then the pokeballButton got enabled and you could click it and break the game or maybe get yourself banned because it would send another catch request for already catched pokemon...

Refactor Busy out of CatchingPage

---

PokemonGo-UWP/ViewModels/CapturePokemonPageViewModel.cs

Changes
-------
- Added check to 0 pokeballs when selecting the same type
Change details
--------------
When I ran out of pokeballs, they didn't change to next type automatically, because `SelectPokeballType` function returned the same type with `.Count == 0` so the line after throw:
`SelectedCaptureItem = SelectPokeballType(LastItemUsed) ?? SelectAvailablePokeBall()` didn't change pokeball type to the next.
Now when `SelectPokeballType` returns null when .Count is 0 it works fine.

Fix when pokeballs goes to 0, they didn't change to next available

---

PokemonGo-UWP/ViewModels/PokedexPageViewModel.cs
PokemonGo-UWP/Views/PokedexPage.xaml
PokemonGo-UWP/Views/PokedexPage.xaml.cs

Closes issues
-------------
Resolves visual bug that occurred only to some user (like @chatfix ) leading to the Pokédex view being unusable.
Changes
-------
- Improved clickable area of Pokédex entries
Change details
--------------
- Removed click event from templates and moved to GridView containing them
- Set MaxWidth and MaxHeight for the ItemContainerStyle
Due to this change, there is now a border visible when hovering over the entries. Should be fixed later on with a custom style an template.

Fixing visual bug on Pokedex

---

PokemonGo-UWP/ViewModels/PokedexPageViewModel.cs

Changes
-------
- Fixed crash introduced in #1544
Change details
--------------
- Fixes bug that caused a crash when tapping on a Pokedex entry for a Pokemon, that was not yet spotted.

Fixed crash in Pokedex

---

PokemonGo-UWP/Utils/Signature/DeviceInfosAndroid.cs
PokemonGoAPI/Login/PtcLogin.cs

- I believe `HorizontalAccuracy` referrs to HDOP and the missing `VerticalAccuracy` refers to VDOP. (We're not using the Android code right now, but this might help on the iOS side too.)
-  Fixing a PtcLogin issue documented on PogoDev. See the code comment for a url referring to the issue in question. I don't want to link to it directly.

Windows GPS Accuracy API + PTC Token Fix

---

PokemonGo-UWP/Strings/en-US/CodeResources.resw
PokemonGo-UWP/ViewModels/PokemonDetailsPageViewModel.cs

Closes issues
-------------
- Closes #1539 
Changes
-------
- Pokémon cannot be transfered, if it's a favorite
Change details
--------------
If the user will Transfer a favorite Pokémon, there will be shown a message, that it's not able to Transfer it. It know, the message is different to the original one, but I think, it Looks better with the PogoMessageDialog.

Cannot transfer Pokémon, if it is a favorite

---

PokemonGo-UWP/Views/GameMapPage.xaml

Closes issues
-------------
- Closes #1258 
Changes
-------
- Changed margins and pic sizes on nearby panel of the main map to show max three pokemons.
Change details
--------------
-Some pokemons appear quite small, but compared to original app they are about the same size if not bigger

Fixed main map's nearby panel to show three pokemons (Take two)

---

PokemonGo-UWP/Views/PokemonDetailPage.xaml

Closes issues
-------------
- Closes #1608 
Changes
-------
- Changed: Size of Pokemon Images in Details page is now bigger
Change details
--------------
Here a screenshot. What dou you mean?

Resized Pokemon Image in Detail Page

---

PokemonGo-UWP/ViewModels/CapturePokemonPageViewModel.cs
PokemonGoAPI/Exceptions/LoginFailedException.cs
PokemonGoAPI/Extensions/CookieContainerExtensions.cs
PokemonGoAPI/Login/PtcLogin.cs
PokemonGoAPI/PokemonGoAPI.csproj
PokemonGoAPI/project.json

Problem arose due to changing HttpClient to static. Because getting the login parameters and Posting the login parameters to get the "ticket" hits the same URL, and we're using the same HttpClient instance, subsequent requests contain the auth "cookie". If you do a GET to that url with a valid AuthCookie, it updates the "ticket" needed to get the OAuthToken.
Allow login request 2 of 3 to accept null parameters, and do a GET instead of a POST if the parameter is null.
STATUS: Awaiting final testing

Fix 30 Minute Login Failure

---

PokemonGo-UWP/Utils/Signature/DeviceInfosIOS.cs

Closes issues
-------------
- Potentially Closes #1343
- Closes #1245
- Fixes issue from #1510 but doesn't closes it.
Changes
-------
- Changes ActivityStatusIOS to use working values
Change details
--------------
As discussed in #1510. Names of vars could be wrong here. I tried every combination of these 6 booleans and Automotive, Running and Walking must be false. Otherwise server returns 0 map objects. Others are set accordingly to speed. Tilt is random, because I don't know if we can get tilt somehow.

HotFix for speed limit

---

PokemonGo-UWP/PokemonGo-UWP.csproj
PokemonGo-UWP/Utils/GameClient.cs
PokemonGo-UWP/Views/ChallengePage.xaml
PokemonGo-UWP/Views/ChallengePage.xaml.cs
PokemonGoAPI/Client.cs
PokemonGoAPI/PokemonGoAPI.csproj
PokemonGoAPI/PokemonGoApiClient.Events.Generated.cs
PokemonGoAPI/Rpc/BaseRpc.cs
PokemonGoAPI/Rpc/Login.cs
PokemonGoAPI/Rpc/Map.cs
PokemonGoAPI/Rpc/Misc.cs

Closes issues
-------------
- Closes #1764 
Changes
-------
- Adds Capcha Support
Change details
--------------
Using changes discussed in #1764 (It's a big conversation)
It may not work, looking for people to test it.

[WIP] Capcha Support
